version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "build"

  - package-ecosystem: "npm"
    directory: "/UI"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ui"
    commit-message:
      prefix: "build"

  - package-ecosystem: "npm"
    directory: "/Android"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "android"
    commit-message:
      prefix: "build"
